version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-javafx
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root*
      MYSQL_DATABASE: main
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # opcional si tienes script

volumes:
  mysql_data:
